dist: xenial
language: node_js
node_js:
  - "10.15.3"

env:
  global:
    - secure: "EII+nju+n/GDWOcE4NV8R8prVeKB4kH9JiHmcZ6kHZF8njL8sUx7JAFSOmilSixyrNyR9ykJW59r4TPckZTT9wNS3kySqOjov+D/qQzZXijnBtOpGJKBtqcJol0oK35keA2eN8uX8us2LaRIA98Hvt993FNeFQENExbGpvCoUILstOQrfGbaLxXg5kXCPFu0l+sBjxWmqk7b4rLFSLjP8NBNzoTshBh4A6N/c1cAvOC64eai+GEgy1qVwISyGabwo8Q+Mv2v0zhnuRsVTe7Hvo+PabniG4+5klqhN9PIxrS22nPOogTLkpE3fOalllL50xzG3OCgdkew1jpV+sxQ9UWEdcFzgYZtDB2WTYHY1P7yWiC9mHZ5eBu1MOzKrRYx1FTvp4ILUtncxeKrbVJ4piG6zBxaNmejsAVWZZ1l5JztfMf/miHUnmVMvg3Lan/dSghLXNtYGUFJPkEyLZcItAEX6u2EbI2OV2mS2Fup57fvPoInR/Tp0EeQX2BAj2H2z1QD5ZT4GWWhU/4gTKS08dkL8DOW4RnjzAsoMbdrDq58FTJ7rGDIxszNFbj2XjDW/dJbuwzFI7HRdzXSpWdth1F01krjt/wqkBJIPh/UpkyPOir2YKYDtnijGnKGcTUNZF/uRwPJeT0u3sbwzz/ae38RNxnqxN9AuPwewT0dYQ8="

if: type = push
script: ./make-commit.sh
